### ISSUE TITLE
Game crashes when making a second action

### ISSUE THREAD

**Issue by nikbrandt** [iChun/Keygrip#3]
As the title says, I can record one action fine, watch it back and everything. But once I click the OK button for a second action, my game crashes. 

Here is the crash report, thanks in advance!

EDIT: The crash report says that I have Java 6, but I have Java 7, and I have reinstalled it, according to java.com/verify I do have Java 7.

ANOTHER EDIT: I found a temporary fix, using MultiMC. I am going to guess this is because MultiMC might be properly tracking the Java version, letting it work. So it would be great if there was a fix to the vanilla launcher way, but MultiMC seems to work for now.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/16/15 10:24 PM
Description: Rendering screen

java.lang.NoSuchMethodError: java.lang.Integer.compare(II)I
    at us.ichun.mods.keygrip.common.scene.action.Action.compareTo(Action.java:450)
    at java.util.Arrays.mergeSort(Arrays.java:1144)
    at java.util.Arrays.sort(Arrays.java:1079)
    at java.util.Collections.sort(Collections.java:115)
    at us.ichun.mods.keygrip.client.gui.window.WindowNewAction.elementTriggered(WindowNewAction.java:137)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementButton.onClick(ElementButton.java:64)
    at us.ichun.mods.ichunutil.client.gui.window.Window.onClick(Window.java:200)
    at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:125)
    at us.ichun.mods.keygrip.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:147)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:427)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1049)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at us.ichun.mods.keygrip.common.scene.action.Action.compareTo(Action.java:450)
    at java.util.Arrays.mergeSort(Arrays.java:1144)
    at java.util.Arrays.sort(Arrays.java:1079)
    at java.util.Collections.sort(Collections.java:115)
    at us.ichun.mods.keygrip.client.gui.window.WindowNewAction.elementTriggered(WindowNewAction.java:137)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementButton.onClick(ElementButton.java:64)
    at us.ichun.mods.ichunutil.client.gui.window.Window.onClick(Window.java:200)
    at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:125)
    at us.ichun.mods.keygrip.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:147)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:427)

-- Screen render details --
Details:
    Screen name: us.ichun.mods.keygrip.client.gui.GuiWorkspace
    Mouse location: Scaled: (200, 206). Absolute: (401, 67)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Creeperman_333'/400, l='MpServer', x=-252.75, y=65.79, z=180.08]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -237.00,64.00,232.00 - World: (-237,64,232), Chunk: (at 3,4,8 in -15,14; contains blocks -240,0,224 to -225,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1711 game time, 1711 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 87 total; [EntityBat['Bat'/129, l='MpServer', x=-259.78, y=34.32, z=201.26], EntityCreeper['Creeper'/828, l='MpServer', x=-197.50, y=15.00, z=122.50], EntityBat['Bat'/128, l='MpServer', x=-259.25, y=39.10, z=197.25], EntityRabbit['Rabbit'/131, l='MpServer', x=-275.09, y=65.00, z=206.41], EntityRabbit['Rabbit'/130, l='MpServer', x=-266.59, y=64.02, z=203.06], EntityCreeper['Creeper'/827, l='MpServer', x=-198.50, y=15.00, z=124.50], EntityZombie['Zombie'/144, l='MpServer', x=-243.94, y=29.00, z=121.47], EntitySquid['Squid'/145, l='MpServer', x=-255.43, y=61.56, z=163.83], EntityCreeper['Creeper'/146, l='MpServer', x=-255.50, y=29.00, z=199.50], EntityBat['Bat'/147, l='MpServer', x=-226.88, y=41.10, z=198.25], EntitySheep['Sheep'/148, l='MpServer', x=-235.84, y=63.00, z=210.72], EntitySheep['Sheep'/149, l='MpServer', x=-242.50, y=63.00, z=210.50], EntitySheep['Sheep'/150, l='MpServer', x=-245.19, y=66.00, z=222.31], EntityPig['Pig'/170, l='MpServer', x=-226.50, y=66.00, z=233.50], EntityPig['Pig'/169, l='MpServer', x=-225.50, y=65.00, z=233.50], EntityPig['Pig'/168, l='MpServer', x=-230.56, y=65.00, z=229.69], EntitySheep['Sheep'/163, l='MpServer', x=-236.97, y=63.00, z=210.53], EntityCreeper['Creeper'/162, l='MpServer', x=-238.53, y=40.00, z=195.03], EntityItem['item.item.seeds'/161, l='MpServer', x=-229.75, y=65.00, z=159.13], EntityPig['Pig'/167, l='MpServer', x=-230.19, y=67.00, z=233.50], EntityPig['Pig'/166, l='MpServer', x=-231.56, y=67.00, z=233.50], EntityPig['Pig'/165, l='MpServer', x=-221.53, y=68.00, z=233.22], EntityPig['Pig'/164, l='MpServer', x=-225.53, y=63.00, z=219.22], EntitySkeleton['Skeleton'/186, l='MpServer', x=-220.31, y=39.00, z=231.66], EntityCreeper['Creeper'/187, l='MpServer', x=-222.50, y=44.00, z=227.50], EntityBat['Bat'/184, l='MpServer', x=-209.25, y=26.10, z=221.31], EntityZombie['Zombie'/185, l='MpServer', x=-208.72, y=20.00, z=216.50], EntityPlayerSP['Creeperman_333'/400, l='MpServer', x=-252.75, y=65.79, z=180.08], EntityPig['Pig'/188, l='MpServer', x=-222.13, y=68.00, z=232.03], EntitySkeleton['Skeleton'/189, l='MpServer', x=-219.50, y=42.00, z=248.50], EntitySkeleton['Skeleton'/59, l='MpServer', x=-332.50, y=12.00, z=251.50], EntitySkeleton['Skeleton'/58, l='MpServer', x=-325.50, y=14.00, z=177.50], EntitySpider['Spider'/57, l='MpServer', x=-325.50, y=14.00, z=182.16], EntityZombie['Zombie'/56, l='MpServer', x=-323.94, y=37.00, z=169.47], EntityZombie['Zombie'/183, l='MpServer', x=-221.44, y=28.00, z=195.28], EntityBat['Bat'/61, l='MpServer', x=-329.14, y=14.53, z=251.75], EntityZombie['Zombie'/180, l='MpServer', x=-215.56, y=26.00, z=192.03], EntitySkeleton['Skeleton'/60, l='MpServer', x=-331.50, y=12.00, z=254.50], EntitySpider['Spider'/205, l='MpServer', x=-206.72, y=20.00, z=218.16], EntityZombie['Zombie'/204, l='MpServer', x=-196.81, y=26.00, z=201.47], EntityItem['item.item.seeds'/207, l='MpServer', x=-195.59, y=64.00, z=227.19], EntityZombie['Zombie'/206, l='MpServer', x=-204.72, y=20.00, z=217.91], EntitySheep['Sheep'/201, l='MpServer', x=-194.19, y=79.00, z=153.44], EntitySheep['Sheep'/200, l='MpServer', x=-201.78, y=78.00, z=157.88], EntityZombie['Zombie'/203, l='MpServer', x=-197.72, y=26.00, z=201.50], EntityPig['Pig'/202, l='MpServer', x=-202.16, y=78.00, z=173.81], EntityPig['Pig'/197, l='MpServer', x=-196.50, y=79.00, z=157.50], EntityPig['Pig'/196, l='MpServer', x=-195.00, y=79.00, z=150.97], EntitySheep['Sheep'/199, l='MpServer', x=-195.81, y=79.00, z=153.44], EntitySheep['Sheep'/198, l='MpServer', x=-197.13, y=79.00, z=154.34], EntitySkeleton['Skeleton'/73, l='MpServer', x=-311.50, y=19.00, z=193.50], EntityPig['Pig'/195, l='MpServer', x=-192.50, y=78.00, z=157.50], EntityZombie['Zombie'/194, l='MpServer', x=-207.50, y=21.00, z=119.50], EntitySkeleton['Skeleton'/84, l='MpServer', x=-298.50, y=45.00, z=197.50], EntitySkeleton['Skeleton'/216, l='MpServer', x=-191.50, y=51.00, z=246.88], EntitySkeleton['Skeleton'/2935, l='MpServer', x=-217.50, y=13.00, z=223.50], EntitySquid['Squid'/83, l='MpServer', x=-296.53, y=60.00, z=192.66], EntityBat['Bat'/219, l='MpServer', x=-179.44, y=34.10, z=259.63], EntityChicken['Chicken'/93, l='MpServer', x=-273.47, y=70.00, z=106.72], EntitySkeleton['Skeleton'/2936, l='MpServer', x=-215.50, y=13.00, z=226.50], EntityBat['Bat'/95, l='MpServer', x=-279.38, y=46.10, z=116.75], EntitySpider['Spider'/214, l='MpServer', x=-191.97, y=29.00, z=244.34], EntityCreeper['Creeper'/3059, l='MpServer', x=-203.50, y=47.02, z=231.50], EntityChicken['Chicken'/94, l='MpServer', x=-280.59, y=71.00, z=107.63], EntityEnderman['Enderman'/215, l='MpServer', x=-188.63, y=51.00, z=248.78], EntityCreeper['Creeper'/3060, l='MpServer', x=-202.50, y=47.02, z=231.50], EntitySkeleton['Skeleton'/208, l='MpServer', x=-204.91, y=42.00, z=242.50], EntityCreeper['Creeper'/3061, l='MpServer', x=-203.50, y=47.02, z=233.50], EntityZombie['Zombie'/102, l='MpServer', x=-280.50, y=50.00, z=191.50], EntityZombie['Zombie'/103, l='MpServer', x=-280.50, y=50.00, z=192.50], EntitySkeleton['Skeleton'/100, l='MpServer', x=-281.50, y=50.00, z=188.50], EntitySkeleton['Skeleton'/101, l='MpServer', x=-281.28, y=50.00, z=182.16], EntityBat['Bat'/98, l='MpServer', x=-276.61, y=12.99, z=186.25], EntitySkeleton['Skeleton'/99, l='MpServer', x=-274.94, y=49.00, z=175.56], EntityBat['Bat'/96, l='MpServer', x=-282.03, y=46.77, z=118.54], EntityChicken['Chicken'/97, l='MpServer', x=-279.53, y=69.00, z=116.34], EntityTrail['unknown'/500, l='MpServer', x=-252.75, y=65.79, z=180.08], EntityRabbit['Rabbit'/104, l='MpServer', x=-282.69, y=67.00, z=207.53], EntityBat['Bat'/105, l='MpServer', x=-271.93, y=16.86, z=215.17], EntityOtherPlayerMP['Creeperman_333'/2554, l='MpServer', x=-251.47, y=65.01, z=176.33], EntitySquid['Squid'/127, l='MpServer', x=-262.56, y=61.88, z=185.96], EntitySquid['Squid'/126, l='MpServer', x=-256.57, y=62.19, z=165.01], EntityPig['Pig'/244, l='MpServer', x=-175.75, y=70.00, z=255.84], EntitySkeleton['Skeleton'/125, l='MpServer', x=-263.50, y=16.00, z=138.50], EntityChicken['Chicken'/124, l='MpServer', x=-268.69, y=69.00, z=113.53], EntityPig['Pig'/242, l='MpServer', x=-174.00, y=70.00, z=248.06], EntityPig['Pig'/240, l='MpServer', x=-173.50, y=70.00, z=249.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2489)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Mac OS X (x86_64) version 10.10.2
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 279686488 bytes (266 MB) / 565432320 bytes (539 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 24, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.20.1290 Minecraft Forge 11.14.0.1290 5 mods loaded, 5 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{8.0.20.1290} [Forge Mod Loader](forge-1.8-11.14.0.1290-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{11.14.0.1290} [Minecraft Forge](forge-1.8-11.14.0.1290-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{5.3.0} [iChunUtil](iChunUtil-5.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Keygrip{5.0.0} [Keygrip](Keygrip-5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.8-Forge11.14.0.1290-1.8
    LWJGL: 2.9.2
    OpenGL: AMD Radeon HD 6770M OpenGL Engine GL version 2.1 ATI-1.30.5, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [faithful32pack-2]
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by iChun** [comment]
You need java 7

**Comment by nikbrandt** [comment]
As I said, I have Java 7, and it works fine with MultiMC. It seems that the vanilla minecraft launcher does not properly detect Java though. I have verified that I have Java 7.. This is more of a bug report for the vanilla MC launcher. Thanks!

**Comment by iChun** [comment]
Ah yeah sorry, I didn't read the edits cause I responded right to the Email. Anyways yeah... I probably should just release a Java 6 compatible version, it's that one function that's causing the issue :/

But yeah, closed, I guess.
